### ISSUE TITLE
为什么docker我无法部署成功，无论compose或者run

### ISSUE THREAD

**Issue by lopins** [fruitbars/simple-one-api#57]
宝塔面板 和 1Panel 面板都无法成功: 有在目录下预先创建 `config.json`

**Comment by fruitbars** [comment]
有错误日志信息吗？

**Comment by lopins** [comment]
> 有错误日志信息吗？

config.json 不是一个文件

```
version: '3.9'

services:
  simple-one-api:
    image: fruitbars/simple-one-api
    container_name: simple-oneapi
    ports:
      - "9090:9090"
    volumes:
      - /www/wwwroot/simple.one.api/config.json:/app/simple-oneapi/config.json
    restart: unless-stopped
```
